spring.application.name=bffappbar

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://db.crzhbjcygwtyspniruxi.supabase.co:6543/postgres?sslmode=require&pgbouncer=true
spring.datasource.username=postgres
spring.datasource.password=Arn10Fiuggi
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false


spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000