spring.application.name=bffappbar

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://db.crzhbjcygwtyspniruxi.supabase.co:6543/postgres
spring.datasource.username=postgres
spring.datasource.password=Arn10Fiuggi
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
